runtime: nodejs14
service: $SERVICE_NAME
instance_class: F1

service_account: $SERVICE_ACCOUNT

handlers:
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html